tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  php_code_sniffer: true
  php_changetracking: true
  php_mess_detector: true
  sensiolabs_security_checker: true
  php_cs_fixer:
    config: { level: psr2 }
build:
  environment:
    php: '7.0'
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'php-clover'
filter:
    excluded_paths: [tests/*, var/*, build/*, web/*]
