tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer: true
    php_changetracking: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_cs_fixer:
        config: { level: psr2 }
build:
    environment:
        php: '7.0'
filter:
    excluded_paths: [tests/*]