language: php

php:
  - '7.0'

cache:
  directories:
    - vendor

before_install:

install:
  - composer install --no-interaction

before_script:

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:

after_failure:

before_deploy:

deploy:
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY #set in environment variables of travis repository settings
  app:
    master: idea-ctp-paula

after_deploy:
