language: php

php:
  - '7.0'

cache:
  directories:
  - vendor

before_install:
install:
- composer install --no-interaction

before_script:
script:
after_script:

after_success:
after_failure:

before_deploy:
deploy:
after_deploy:
