language: php

php:
  - '7.0'

cache:
  directories:
    - vendor

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script:

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:

after_success:

after_failure:

before_deploy:

deploy:
  provider: heroku
  strategy: api
  api_key:
    master: $HEROKU_API_KEY
  app:
    master: idea-ctp-paula
  run:
    - heroku config:set SYMFONY_ENV=prod

after_deploy:
